I Fri-08:47:19.656: 210.01       8.8396680    14.50624     161.69677    100          8.13       
E Fri-08:47:19.656: 210.0108163356781s - progress_reporting timeout!!
Suspender SuspendFloor(EpicsSignalRO(read_pv='PA:12ID:STA_A_FES_OPEN_PL', name='FE_shutter_pss_state', parent='FE_shutter', value=1, timestamp=1761315204.18303, auto_monitor=True, string=False), sleep=0, pre_plan=None, post_plan=None, tripped_message=) reports a return to nominal conditions. Will sleep for 0 seconds and then release suspension at 2025-10-24 09:13:24.
I Fri-09:14:56.470: HDF5 file complete: /share1/USAXS_data/2025-10/10_20_Jun/xueyi/xueyi_usaxs/XY_20Mg2Co_insitu_2863sec_1099.h5
Suspender SuspendBoolLow(EpicsSignalRO(read_pv='usxLAX:blCalc:userCalc1', name='usaxs_CheckBeamStandard', value=0.0, timestamp=1761313437.599123, auto_monitor=False, string=False), sleep=0, pre_plan=None, post_plan=None, tripped_message=) reports a return to nominal conditions. Will sleep for 0 seconds and then release suspension at 2025-10-24 09:14:57.
E Fri-09:14:57.762: Subscription value callback exception (EpicsSignalRO(read_pv='usxLAX:blCalc:userCalc1', name='usaxs_CheckBeamStandard', value=0.0, timestamp=1761313437.599123, auto_monitor=False, string=False))
Traceback (most recent call last):
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/ophyd/ophydobj.py", line 492, in inner
    cb(*args, **kwargs)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/suspenders.py", line 141, in __call__
    raise RuntimeError("Could not create the ")
RuntimeError: Could not create the 
I Fri-09:14:57.778: Starting collection of SAXS for XY-20Mg2Co-insitu_4747sec
Exception in thread Thread-855066 (move_it):
Traceback (most recent call last):
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/devices/shutters.py", line 215, in move_it
    self.open()
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/devices/shutters.py", line 650, in open
    self.wait_for_state(self.pss_state_open_values, timeout=timeout)
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/devices/shutters.py", line 642, in wait_for_state
    raise TimeoutError(msg)
TimeoutError: Timeout (10 s) waiting for shutter state to reach a value in [1, 'O', 'N']

and then 



None
I Fri-09:18:33.725: tuning axis: a_stage_r
E Fri-09:18:33.732: Error in tune_ar: shutter is operating
E Fri-09:18:33.732: Error in tune_usaxs_optics: shutter is operating
E Fri-09:18:33.732: Run aborted
Traceback (most recent call last):
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py", line 1584, in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/plans/labels_to_streams.py", line 242, in label_stream_wrapper
    return (yield from bpp.plan_mutator(plan, action[when.value]))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 89, in plan_mutator
    msg = plan_stack[-1].throw(exception)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 1375, in __call__
    return (yield from plan)
            ^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 1228, in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 89, in plan_mutator
    msg = plan_stack[-1].throw(exception)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 845, in monitor_during_wrapper
    return (yield from plan2)
            ^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 89, in plan_mutator
    msg = plan_stack[-1].throw(exception)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 89, in plan_mutator
    msg = plan_stack[-1].throw(exception)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 907, in fly_during_wrapper
    return (yield from plan2)
            ^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 89, in plan_mutator
    msg = plan_stack[-1].throw(exception)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 89, in plan_mutator
    msg = plan_stack[-1].throw(exception)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams11/USAXS/bits_usaxs/src/usaxs/plans/axis_tuning.py", line 607, in tune_usaxs_optics
    yield from tune_ar(md=md)
  File "/home/beams11/USAXS/bits_usaxs/src/usaxs/plans/axis_tuning.py", line 157, in tune_ar
    yield from bps.mv(
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 1952, in __iter__
    return (yield from self._iter)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/plan_stubs.py", line 390, in mv
    ret = yield Msg("set", obj, val, group=group, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 206, in plan_mutator
    inner_ret = yield msg
                ^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 206, in plan_mutator
    inner_ret = yield msg
                ^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py", line 206, in plan_mutator
    inner_ret = yield msg
                ^^^^^^^^^
  [Previous line repeated 3 more times]
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py", line 1676, in _run
    new_response = await coro(msg)
                   ^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/opentelemetry/util/_decorator.py", line 71, in async_wrapper
    return await func(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py", line 2279, in _set
    ret = obj.set(*msg.args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/devices/shutters.py", line 199, in set
    raise RuntimeError("shutter is operating")
RuntimeError: shutter is operating
Traceback (most recent call last):
  Cell In[312], line 1
    RE(tune_usaxs_optics())
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:973 in __call__
    plan_return = self._resume_task(init_func=_build_task)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:1120 in _resume_task
    raise exc
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:1755 in _run
    raise err
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:1584 in _run
    msg = self._plan_stack[-1].throw(stashed_exception or resp)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/plans/labels_to_streams.py:242 in label_stream_wrapper
    return (yield from bpp.plan_mutator(plan, action[when.value]))
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:89 in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:1375 in __call__
    return (yield from plan)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:1228 in baseline_wrapper
    return (yield from plan_mutator(plan, insert_baseline))
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:89 in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:845 in monitor_during_wrapper
    return (yield from plan2)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:89 in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:89 in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:907 in fly_during_wrapper
    return (yield from plan2)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:89 in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:89 in plan_mutator
    msg = plan_stack[-1].throw(exception)
  File /home/beams11/USAXS/bits_usaxs/src/usaxs/plans/axis_tuning.py:607 in tune_usaxs_optics
    yield from tune_ar(md=md)
  File /home/beams11/USAXS/bits_usaxs/src/usaxs/plans/axis_tuning.py:157 in tune_ar
    yield from bps.mv(
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/utils/__init__.py:1952 in __iter__
    return (yield from self._iter)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/plan_stubs.py:390 in mv
    ret = yield Msg("set", obj, val, group=group, **kwargs)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:206 in plan_mutator
    inner_ret = yield msg
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:206 in plan_mutator
    inner_ret = yield msg
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:206 in plan_mutator
    inner_ret = yield msg
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:206 in plan_mutator
    inner_ret = yield msg
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:206 in plan_mutator
    inner_ret = yield msg
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/preprocessors.py:206 in plan_mutator
    inner_ret = yield msg
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:1676 in _run
    new_response = await coro(msg)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/opentelemetry/util/_decorator.py:71 in async_wrapper
    return await func(*args, **kwargs)  # type: ignore
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/bluesky/run_engine.py:2279 in _set
    ret = obj.set(*msg.args, **kwargs)
  File ~/.conda/envs/bits_usaxs/lib/python3.11/site-packages/apstools/devices/shutters.py:199 in set
    raise RuntimeError("shutter is operating")
RuntimeError: shutter is operating


In [313]: e
 

after abort.


at exit:
In [314]: exit
E Fri-09:19:22.478: Task was destroyed but it is pending!
task: <Task pending name='Task-983877' coro=<Event.wait() running at /home/beams/USAXS/.conda/envs/bits_usaxs/lib/python3.11/asyncio/locks.py:213> wait_for=<Future pending cb=[Task.task_wakeup()]>>
(base) usaxs@usaxscontrol .../USAXS_data/2025-10 $ 

